### ISSUE TITLE
Dificuldade na configuração do Sass

### ISSUE THREAD

**Issue by guilhermemarconi** [vtex/speed#10]
Não consigo configurar o `Gruntfile` para compilar meus arquivos `.scss`. Ao salvar, recebo o aviso de que não foi encontrado nenhum arquivo `.scss`.

Utilizo o [`grunt-contrib-compass`](https://github.com/gruntjs/grunt-contrib-compass#options) e, mesmo configurando os diretórios iguais ao `less`, recebo este mesmo aviso.

```
Verifying property compass.main exists in config...OK
File: [no files]
Options: 0={"sassDir":"src/scss/","cssDir":"build/","outputStyle":"nested","assetCacheBuster":false,"raw":"preferred_syntax = :scss\r\n"}
Compass can't find any Sass files to compile.
Is your compass configuration correct?.
```

Alguém já passou por algum problema semelhante?

> _Obs.: já utilizo esta dependência em meus projetos há bastante tempo e nunca tive problemas._

**Comment by firstdoit** [comment]
Ok @guilhermemarconi. Você consegue criar um repo para reproduzir o problema? Sinto que ele não diz respeito ao escopo do *speed*.

**Comment by guilhermemarconi** [comment]
Pois é, @firstdoit, eu imaginei que não seria, mesmo, do escopo principal. Inclusive peço desculpas por solicitar isso aqui.

Assim que estiver um tempinho livre aqui na agência, ou até mesmo em casa, crio um repo e edito esse comentário com ele aqui. :grin:

**Comment by firstdoit** [comment]
Ok, @guilhermemarconi. Enquanto isso, vou fechar a issue por que acho que não é do escopo do Speed, já que sequer ele vem com `compass` configurado.

**Comment by guilhermemarconi** [comment]
@firstdoit vim apenas informar que, após conversar contigo no VTEX Developer Day, testei novamente o Speed e o `Sass` funcionou corretamente! :wink: 

Agora é só eu me adaptar à estrutura que do Speed, que é um pouco diferente da minha, para começar a utilizar com frequencia nas implantações.

Thanks! :smile:

**Comment by brenoc** [comment]
:+1:

**Comment by firstdoit** [comment]
Show!
