### ISSUE TITLE
Orders and Login

### ISSUE THREAD

**Issue by zeluizr** [vtex/speed#12]
No vtexlocal, eu não estou conseguindo usar o Orders, nem a página de login.
Não carrega o lightbox com a opção de logar.

**Comment by firstdoit** [comment]
@zeluizr algo no console? Funciona no commercebeta? Tá usando https?

**Comment by zeluizr** [comment]
sim estou usando HTTPS, e funciona no Beta sim!

**Comment by firstdoit** [comment]
@zeluizr não vou conseguir ver isso agora, já que estamos focando no portal novo pra justamente acabar com a necessidade dessa ferramenta.

Se você conseguir descobrir o problema, aceitamos o pull request!

**Comment by carloschneider** [comment]
@firstdoit alguma previsão para o novo portal?

**Comment by firstdoit** [comment]
@carloschneider não posso dar prazos :( mas estamos nos esforçando para o mais breve possível!

**Comment by zeluizr** [comment]
@firstdoit, muito obrigado!

Ze Luiz Rodrigues
eCommerce | User Experience Manager
Av. Pueyrredon 468 Piso 10 - C.A.B.A.
1191AAA - Bs. As. - Argentina
+54 11 4959 6967
+54 9 11 3637 6670
www.fravega.com

**Comment by carloschneider** [comment]
Também estou tentando acessar páginas com https criadas pelo portal. Alguma novidade a respeito disso?

**Comment by brenoc** [comment]
Oi, @carloschneider, infelizmente não. Caso consiga solucionar o problema e submeter um pull request, seria muito bem vindo.

**Comment by carloschneider** [comment]
@brenoc Estou tentando arrumar uma solução. Com certeza se conseguir irei fazer o pull request. Mas seria interessante, se possível, compartilhar um pouco de como funciona a mecânica e os apontamentos do proxy do vtex speed. Facilitaria bastante.
