### ISSUE TITLE
API Search e Vtex.js

### ISSUE THREAD

**Issue by zeluizr** [vtex/speed#18]
Fala ai galera,

Então a API de Search e o Vtex.js não estão funcionando no Speed, sabem porque?

Obrigado.

Ze Luiz Rodrigues
eCommerce | User Experience Manager
Av. Pueyrredon 468 Piso 10 - C.A.B.A.
1191AAA - Bs. As. - Argentina
+54 11 4959 6967
+54 9 11 3637 6670
www.fravega.com

**Comment by brenoc** [comment]
@zeluizr pode dar um exemplo?

**Comment by zeluizr** [comment]
Essa função por exemplo não funciona, quero retornar dados do carrinho e não funciona.
```
vtexjs.checkout.getOrderForm().done( function( orderForm ) {
  console.log( orderForm );
} );
```

**Comment by brenoc** [comment]
@zeluizr Testei por aqui e não consegui reproduzir o erro. Poderia me descrever um cenário pra reproduzir o erro?

**Comment by zeluizr** [comment]
@brenoc, eu simplismente tento rodar o Vtex.js o Catalog funciona porém o OrderForm não.
![Error](http://fravega.com/arquivos/error_1.png)
![Error](http://fravega.com/arquivos/error_2.png)
![Error](http://fravega.com/arquivos/error_3.png)

E quando rodo alguma API, como por exemplo Search, também não me responde.

![Error](http://fravega.com/arquivos/error_4.png)
![Error](http://fravega.com/arquivos/error_5.png)

Na verdade ele retorna o JSON, porém não imprime dizendo que o Cross Domain não tem permissão para o vtexlocal, porém se rodo isso em produção (www.fravega.com), funciona perfeitamente.

**Comment by brenoc** [comment]
@zeluizr testei a chamada ao Checkout e respondeu tudo certo:
```js
vtexjs.checkout.getOrderForm().done(function(data) { console.log(data); })
```
Console:
```
Object {readyState: 1}
Object {orderFormId: "ac3b9e96ca9846bb97607302491aa4b5", salesChannel: "1", loggedIn: false, checkedIn: false, allowManualPrice: false…}
```

Quanto as chamadas ao Catálogo, realmente alguma coisa está fazendo com que o JSON dos requests fiquem truncados. Isso faz com que o jQuery não consiga parsear o JSON.

Se você colocar o handler de erro, poderá ver que cai nele:

```js
$.ajax({
  type: "GET",
  url: "/api/catalog_system/pub/products/search/12345"
}).success( function( data ) {
  console.log("Imprimindo console aqui");
  console.log(data.productName);
}).fail( function(data) {
  console.log("Fail", data);
});
```
Console:
```
Fail Object {readyState: 4, responseText: "[{"productId":"2012777","productName":"PLANCHITA D…heckout":"bce26ca23489988df741ac7a258e90e3_"}}]}]", status: 200, statusText: "OK"}
``` 

Vi que o problema não acontece sem o `middleware.replaceHtmlBody(environment)` do `Gruntfile.coffee`.

Poderia mudar o array de middlewares do `Gruntfile.coffee` para esse:
```
middleware: [
  middlewares.disableCompression
  httpPlease(host: portalHost, verbose: verbose)
  serveStatic('./build')
  proxy(imgProxyOptions)
  proxy(portalProxyOptions)
  middlewares.replaceHtmlBody(environment)
  middlewares.errorHandler
]
```

E ver se tudo funciona?

**Comment by brenoc** [comment]
PS: da próxima vez seria maneiro se pudesse colocar os trechos de código como texto no comentário, isso facilitaria muito meus testes. Tive que copiar tudo na mão :(

**Comment by zeluizr** [comment]
@brenoc, sorry!
Vou testar!

**Comment by zeluizr** [comment]
@brenoc, não funcionou!

Te explico porque, com a troca do `middleware` no `Gruntfile` ele deixa de apontar para os arquivos locais e aponta para o `fravega.vteximg.com.br` e não lê mais os meus arquivos locais.
