### ISSUE TITLE
Html no vtex speed

### ISSUE THREAD

**Issue by DCitalo** [vtex/speed#20]
Olá eu sou novo no uso de vtex speed e queria saber ate onde eu consigo editar uma pagina so no local, por exemplo estou tentando mudar o html pelo proprio vtex speed do mesmo jeito que estou fazendo com o style.css, mas ele acaba carregando o html que está no vtexcommerceestable, como conserto isso? ou não tem como consertar e o vtex speed so seria um adianto para o css e js? Obrigado pela atenção,
Ítalo Drago.

**Comment by brenoc** [comment]
@DCitalo, exato, o VTEX Speed é focado no desenvolvimento dos arquivos estáticos (JS, CSS).
