### ISSUE TITLE
Problemas com vtexlocal

### ISSUE THREAD

**Issue by carloschneider** [vtex/speed#22]
Mais alguém está enfrentando problemas com o vtexlocal.com.br? @brenoc

**Comment by francosabolo** [comment]
Sí a mí tampoco me funciona !

**Comment by carloschneider** [comment]
Já estamos há uma semana mais ou menos sem o vtexlocal.com.br, tem dificultado bastante.

**Comment by nahuelsanchez** [comment]
What problems are you facing?

**Comment by brenoc** [comment]
Hi, everyone, can you guys update your package.json with the new one and test it again, please? We've updated a bunch of the dependencies, maybe that will make it work.

Oi, pessoal, vocês podem atualizar o package.json e testar novamente, por favor? Nós atualizamos diversas dependências, talvez isso faça com que funcione.

https://github.com/vtex/speed/blob/master/package.json

**Comment by brenoc** [comment]
If even after the update it doesn't work, can you tell which accountName and environment is set in your `Gruntfile.coffee` and more details on how to reproduce.

Se mesmo após as atualizações não funcionar, você pode me dizer qual accountName e environment está setado no seu `Gruntfile.coffee` e mais detalhes de como reproduzir.

**Comment by carloschneider** [comment]
Voltou a funcionar sem precisar atualizar os módulos, obrigado. Acredito que era algum problema com o domínio vtexlocal.com.br.

**Comment by brenoc** [comment]
@carloschneider ótimo, obrigado! Fechando a issue :+1:
