### ISSUE TITLE
Vtex trabaja con SASS

### ISSUE THREAD

**Issue by jlcallalle** [vtex/speed#23]
Hola, estan e su planes, cambiar el compilador LESS a SASS?

**Comment by brenoc** [comment]
Hi, @jlcallalle, VTEX Speed it's just a boilerplate, you can easily extend it to make it your own.

To use SASS just add [grunt-contrib-sass](https://github.com/gruntjs/grunt-contrib-sass).

It will look something like this in you `Gruntfile.coffee`:
```coffee
    sass:
      main:
        files: [
          expand: true
          cwd: 'src/'
          src: ['**/*.scss']
          dest: "build/"
          ext: '.css'
        ]
```

Also, remember to change all the references of `less` to `sass`.
