### ISSUE TITLE
Error nginx vtexlocal.com.br

### ISSUE THREAD

**Issue by carloschneider** [vtex/speed#24]
504 Gateway Time-out

nginx

**Comment by RomuloClickqi** [comment]
@carloschneider, também estou passando por essa instabilidade.

**Comment by carloschneider** [comment]
@RomuloClickqi Já não é a primeira vez que isso acontece. Nos últimos 2 meses acho que houveram umas 2 ou 3 quedas do Nginx. Complicado.

**Comment by brenoc** [comment]
Estamos com um problema no ambiente beta, estamos corrigindo. Também estamos sofrendo com isso, quando tiver tudo resolvido, dou um ping aqui.

**Comment by RomuloClickqi** [comment]
@brenoc  Obrigado man !

**Comment by brenoc** [comment]
@RomuloClickqi @carloschneider o problema foi resolvido :grin:

**Comment by RomuloClickqi** [comment]
vlw (y)
