### ISSUE TITLE
Gateway Timeout

### ISSUE THREAD

**Issue by RomuloClickqi** [vtex/speed#25]
Com uma certa frequência o speed vem apresentando um problema. Ele tenta achar um favicon.ico e da erro 504. O erro é intermitente, por isso, não conseguimos simulá-lo. Hoje (06/07/2016) o speed esta apresentando essa instabilidade.

**Erro:** GET http://{nomedaloja}.vtexlocal.com.br/favicon.ico 504 (Gateway Timeout)

**Comment by brenoc** [comment]
@RomuloClickqi acredito que esse erro tenha começado hoje, certo?

O ambiente beta está instável, estamos consertando. Quando resolvermos dou um ping aqui, pra ver se o problema continua.

**Comment by brenoc** [comment]
Vou mover a discussao para a outra issue https://github.com/vtex/speed/issues/24
