### ISSUE TITLE
Falha nas requisições JSON

### ISSUE THREAD

**Issue by eduardoturconi** [vtex/speed#26]
Como resolver?

**Comment by brenoc** [comment]
@eduardoturconi poderia criar um cenário com passo a passo de como reproduzir o erro, por favor?

**Comment by eduardoturconi** [comment]
Qualquer chamada ao vtexjs não executa o callback done(), apenas o fail(), com o JSON incompleto (faltando algum pedaço no final, o que ocasiona falha no parse).

**Comment by carloschneider** [comment]
@firstdoit @brenoc Estou tendo o mesmo problema com vtexjs. O erro para mim acontece apenas quando adiciono um produto no carrinho e tento consumir o getOderForm(). Ex.:

```
vtexjs.checkout.getOrderForm().then(function (orderForm) {
  console.log(orderForm);
});
```

Aparentemente a vtex está mandando dados que normalmente não mandaria no ambiente de produção. O resultado dessa consulta é um JSON de 1268 linhas com a última linha quebrada:

`"ratesAndBenefitsData":nul`

E acaba não terminando de fechar o objeto.

**Comment by eduardoturconi** [comment]
É esse o erro que dava para mim, agora não está mais dando. 
O JSON vem incompleto, e todas as chamadas caem no callback fail().

No momento não estou conseguindo reproduzir a falha.

**Comment by carloschneider** [comment]
Pra mim esse erro só ocorreu ao pegar informações do orderForm com produtos no carrinho. Com o carrinho vazio funciona.

**Comment by brenoc** [comment]
Talvez tenha a ver com o tamanho do JSON.

**Comment by carloschneider** [comment]
É possível.

**Comment by firstdoit** [comment]
Oi, galera. Já consegui reproduzir o problema. Ele está no middleware `replaceHtmlBody`. Tirando essa linha funciona:

`middlewares.replaceHtmlBody(environment)`

Mas as imagens não vão mais aparecer.

Segunda feira devo conseguir subir a solução, OK? Desculpem a demora.

**Comment by firstdoit** [comment]
Fala, galera.

Consegui resolver o bug. O problema era o seguinte:

Ao proxiar os requests, nós reescrevemos as respostas que contém `vteximg`, para que apontem para `vtexlocal` e vocês possam mudar imagens pelo proxy. Entretanto, essa mudança no conteúdo da resposta não era refletida no header `Content-Length`, que era mandado com o valor original do servidor da VTEX.
Ou seja, se vinha uma resposta com `700` bytes, depois da alteração poderia ter `740` mas o header ainda dizia `700`. Assim, as respostas eram "cortadas pela metade" pelos browsers (corretamente).

A versão em master já corrige esse problema, reescrevendo o header após as substituições no corpo do request. https://github.com/vtex/speed/commit/099b2879a5cfca99b884a94bb8ef1fcd0002fba2

Desculpa pela demora, mas estamos muito focados em trazer a nova plataforma, que vai aposentar definitivamente essa ferramenta aqui!

Abraços

**Comment by carloschneider** [comment]
@firstdoit vi que você usou o Buffer:

`proxiedHeaders['content-length'] = Buffer.byteLength(data)`

Mas ele não é definido em nenhum lugar.

**Comment by firstdoit** [comment]
@carloschneider o `Buffer` é um global no Node :)
https://nodejs.org/api/globals.html#globals_class_buffer

**Comment by carloschneider** [comment]
@firstdoit só fui testar essa nova versão agora, mas estou tendo o seguinte problema:

```
/Users/carlo/Documents/avanti/vtex-gulp/gulpfile.js:112
            proxiedHeaders['content-length'] = Buffer.byteLength(data);
                                             ^
TypeError: Cannot set property 'content-length' of null
    at ServerResponse.res.end (/Users/carlo/Documents/avanti/vtex-gulp/gulpfile.js:112:46)
    at ServerResponse.res.end (/Users/carlo/Documents/avanti/vtex-gulp/node_modules/connect-http-please/index.js:110:22)
    at ReadStream.onend (_stream_readable.js:517:10)
    at ReadStream.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Isso ocorreu quando inseri um imagem no ambiente local que não existe no servidor.

**Comment by firstdoit** [comment]
Oi, @carloschneider. O que é esse gulp-vtex? :)

**Comment by carloschneider** [comment]
É o mesmo ambiente, só que montado em gulp. Os middlewares do connect são os mesmos.

**Comment by brenoc** [comment]
@carloschneider a gente faz isso, talvez vc tenha que fazer algo parecido com essas linhas:

https://github.com/vtex/speed/blob/099b2879a5cfca99b884a94bb8ef1fcd0002fba2/speed-middleware.coffee#L15-L19
