### ISSUE TITLE
Ambientes Stable e Beta

### ISSUE THREAD

**Issue by carloschneider** [vtex/speed#29]
O pessoal aqui da agência notou que trabalhando com o vtexlocal o ambiente rodado é o beta (vtexcommercebeta) ao invés do stable. Mesmo passando a url do stable pro Proxy no `#{environment}`.

`portalHost = "#{accountName}.#{environment}.com.br"`

O problema é que, até onde conseguimos notar, a página /account/orders é muito diferente nos dois ambientes (stable e beta). O stable é o que está rodando nas lojas atualmente. E isso gera um pouco de dor de cabeça na hora de desenvolver no vtexlocal, pois é bem diferente.

**Comment by brenoc** [comment]
Oi, @carloschneider, tem razão.

Uma solução paliativa é trocar esta linha para `false`:
https://github.com/vtex/speed/blob/master/Gruntfile.coffee#L23

O problema é que o Checkout não funciona com ela como `false`. Para desenvolver no Checkout teria que voltar ela para `true`.

Quero resolver esta questão para que isso não tenha que ser mexido.
Provavelmente terei mais respostas na semana que vem. Enquanto isso, recomendo o uso do workaround proposto.

**Comment by carloschneider** [comment]
@brenoc Alguma novidade com relação a isso?

**Comment by brenoc** [comment]
@carloschneider perdão, acabei esquecendo disso. Amanhã vou conversar com o cara do time que pode resolver isso.

**Comment by carloschneider** [comment]
@brenoc Conseguiu ver essa questão?

**Comment by brenoc** [comment]
@carloschneider sim, conversei com ele e investigamos o que causa isso. Descobrimos que para corrigir o problema teríamos que mexer em uma parte crítica do sistema. Por conta disso, acreditamos que o risco das mudanças nessa parte de nossa infraestrutura não compensa os benefícios que isso nos traz.
Espero que entenda nossa decisão.

Quanto ao My Orders estar diferente da versão em stable, em breve o que está em beta será o novo My Orders, então, logo logo isso vai ser menos problemático pro seu desenvolvimento.

**Comment by carloschneider** [comment]
Perfeito, obrigado @brenoc :)
