### ISSUE TITLE
Speed deixou de funcionar no checkout.

### ISSUE THREAD

**Issue by zeluizr** [vtex/speed#30]
Sempre consegui testar o checkout pelo Speed, porém faz uns meses que deixou de funcionar.
Na verdade está intermitente.
Sabe informar se não pode mais usar? Ou se tenho que configurar algo?

Abrs.,

**Comment by brenoc** [comment]
Oi, @zeluizr, não soubemos de nenhum problema desse tipo. Deveria funcionar normalmente. 

Você poderia dar mais detalhes de quando não funciona? É em alguma página especifica? Qual versão do node você está usando?

Atualizamos algumas dependencias antigas do Speed, poderia conferir se atualizando para estas: https://github.com/vtex/speed/blob/master/package.json funciona? Recomendo depois de atualizar este arquivo apagar a pasta `node_modules` e dar `npm install` no terminal novamente.

**Comment by zeluizr** [comment]
Fala ai @brenoc, então... estou com tudo atualizado, porém quando avanço para o checkout, ele não abre o checkout com loja.vtexlocal.com.br/checkout/#/cart, entendeu.

Esse é o erro do terminal.
`HTTPlease: location hostname and url matches request https://xlshop.vtexlocal.com.br/checkout/
HTTPlease: follow redirect to https://xlshop.vtexcommercestable.com.br
HTTPlease: location hostname and url matches request https://xlshop.vtexlocal.com.br/checkout/
HTTPlease: follow redirect to https://xlshop.vtexcommercestable.com.br
HTTPlease: location hostname and url matches request https://xlshop.vtexlocal.com.br/checkout/
HTTPlease: follow redirect to https://xlshop.vtexcommercestable.com.br`

Print com erro no browser.
![Erro](http://image.prntscr.com/image/a780f51c39a240b6a3e8b848e2e8664b.png)

**Comment by klzns** [comment]
Acredito que o erro tenha sido corrigido com o fix contemplado em #33
