### ISSUE TITLE
Fazer funcionar em https

### ISSUE THREAD

**Issue by rivailruiz** [vtex/speed#32]
Será que seria possível funcionar em Https ? Atualmente, quando uma loja é migrada para https, o vtexlocal para de funcionar.

Edit: Acho que não é possível fazer proxy com https =/

**Comment by carloschneider** [comment]
@firstdoit @klzns Alguma novidade a respeito disso? Aqui na Avanti também temos o mesmo problema.

**Comment by rivailruiz** [comment]
Provavelmente eu irei desenvolver algo com webpack e parar de usar o vtexspeed.

**Comment by rafaeln1** [comment]
Estou tendo o mesmo problema. Alguma posição de correção para o VTEX Speed?

**Comment by klzns** [comment]
@rafaeln1 @rivailruiz @carloschneider 

Oi, pessoal, desculpa a demora na resposta. Não temos uma solução para o problema e, atualmente, não temos ninguém que possa trabalhar nessa questão.

Gostaria de transformar esse tópico em possíveis alternativas open source para o VTEX Speed que a comunidade venha a desenvolver.

Pull requests com a correção deste bug também são bem vindos.

**Comment by carloschneider** [comment]
@klzns 

Então, estou tentando fazer funcionar. Troquei tudo pra HTTPS, alterei a porta, gerei um certificado e etc. O que eu obtive foi o seguinte:

`Error: Hostname/IP doesn't match certificate's altnames: "Host: ofner.vtexlocal.com.br. is not in the cert's altnames: DNS:*.vtex.com.br, DNS:vtex.com.br, DNS:*.vtexcommerce.com.br, DNS:*.vtexcommercestable.com.br, DNS:*.vtexcommercebeta.com.br, DNS:*.vtexcrm.com.br, DNS:*.vteximg.com.br"`

**Comment by deniscsz** [comment]
@klzns @carloschneider @rafaelbac @rivailruiz @firstdoit 
Aqui na agência conseguimos fazer rodar com https. Iremos fazer um PR hoje ainda, após validarmos em outras contas e estiver tudo Ok.
