### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by di3gof3rn4ndes** [vtex/speed#34]
Boa tarde Breno!

Estou com uma dúvida referente  ao VTEX Speed.
Ao acessar localmente http://gobiz.vtexlocal.com.br/, aparece a seguinte mensagem:

Esta página não está funcionando
Redirecionamento em excesso por gobiz.vtexlocal.com.br
Tente limpar os cookies.

ERR_TOO_MANY_REDIRECTS (edited)

No grunt, aparentemente está rodando:

C:\clientes\gobiz>npm start

vtex-speed@4.0.0 start C:\clientes\gobiz

grunt

(node:10872) ExperimentalWarning: The http2 module is an experimental API.

Running "clean:main" (clean) task

> 1 path cleaned.

Running "copy:main" (copy) task

Created 6 directories, copied 4 files

Running "sprite:all" (sprite) task

Files "build/sprite.css", "build/spritesheet.png" created.

Running "coffee:main" (coffee) task

> 1 files created.

Running "less:main" (less) task

> 1 stylesheet created.

Running "imagemin:main" (imagemin) task

Minified 3 images (saved 540 B)

Running "connect:http" (connect) task

Started connect web server on http://localhost:80

Running "watch" task

Waiting...

**Comment by klzns** [comment]
Subi um fix que soluciona o problema. Obrigado pelo report.

**Comment by di3gof3rn4ndes** [comment]
Muito obrigado @klzns

**Comment by tunadao1** [comment]
@klzns eu ainda continuo com o mesmo problema em http://photongroup.vtexlocal.com.br/

O mais engraçado é que o /admin funciona.

**Comment by klzns** [comment]
@tunadao1 testei com a configuração `secureUrl: false` no `package.json` e apareceu td corretamente:

![image](https://user-images.githubusercontent.com/284515/38752931-303afda4-3f33-11e8-9558-ee3509e3244c.png)
