### ISSUE TITLE
My Vtex speed doesn't work , When the page in production https:// 

### ISSUE THREAD

**Issue by jlcallalle** [vtex/speed#36]
My Vtex speed doesn't work , When the page in production https://  , what config I could do, maybe in gruntfile ??

**Comment by klzns** [comment]
@jlcallalle can you update your `Gruntfile.coffee`, `package.json` and `speed-middlewares.coffee` files and check if the error still occurs?

There were a issue about this here: #32 
That was later fixed in this PR: #33

So I think if you update those files, that might solve your issue.

**Comment by jlcallalle** [comment]
Thanks, also and I edit file package.json, another things, 
If I want to use sass (scss) when I could do?

**Comment by klzns** [comment]
Then you have to configure the `Gruntfile.coffe` yourself.

You can check this issue: #23
