### ISSUE TITLE
Loop Infinito en Ambiente local

### ISSUE THREAD

**Issue by chrisar45** [vtex/speed#42]
Desde el viernes mas o menos 03/08/2018, a la hora de entrar a vtex speed se solicita logeo y queda en un loop como que nunca se logea, alguna idea? Tema de codigo yo lo descarto ya que lo venía usando toda la semana y en un refres entró en ese loop, Alguna Idea?

**Comment by klzns** [comment]
Can you update your `Gruntfile.coffee`, `package.json` and `speed-middlewares.coffee` files, delete the `node_modules` folder and install npm dependencies again and check if the error still occurs?

**Comment by chrisar45** [comment]
No, sigo en el Loop

**Comment by profite** [comment]
Aqui o problema persiste também. Começamos a notar no sábado pela manhã em projetos que já rodavam vtexlocal normalmente.

**Comment by profite** [comment]
@chrisar45 , resolvido por aqui. Foi só fazer os updates que rolaram nos últimos commits do repo e funcionou.

**Comment by chrisar45** [comment]
@profite yo actualice los archivos hace más o menos 1 mes funciono todo bien y desde el viernes que está roto y no deja entrar luego de logueado queda en un loop infinito.
![image](https://user-images.githubusercontent.com/19915537/43778955-7093d768-9a2d-11e8-90a0-848e741f2e34.png)
las últimas actualizaciones fueron antes de yo bajarme las últimas, no veo actualizaciones recientes.... alguna idea

**Comment by profite** [comment]
En este caso, no.

**Comment by chrisar45** [comment]
entonces, no le encuentro logica del porque de una momento al otro dejo de registrarme el login, me explico?

**Comment by MScevola** [comment]
Nenhuma solução ainda para este problema???

**Comment by klzns** [comment]
@MScevola @chrisar45  What account are you using? It works fine on the stores I'm trying.

**Comment by chrisar45** [comment]
En todos los proyectos que la agencia trabaja

**Comment by klzns** [comment]
We have some ideas of what might have affected this. We are investigating. Thanks for your patience :)

**Comment by MScevola** [comment]
volvo and sky projects

**Comment by MScevola** [comment]
ok, thanks

**Comment by klzns** [comment]
We just checked our suspicion and apparently it doesn't affect this.

I managed to run volvotrucks just fine:
![image](https://user-images.githubusercontent.com/284515/43851587-790d45d4-9b11-11e8-9eb8-f7a0e5c663d1.png)
 

I would appreciate if you could provide more evidence of the error, so I can help you.

**Comment by chrisar45** [comment]
Esto me tira cuando realizo en linux "sudo npm i"
![image](https://user-images.githubusercontent.com/19915537/43855624-99a82948-9b1c-11e8-860d-7fb5f59983bd.png)

**Comment by klzns** [comment]
Which version of node and npm you are using?

**Comment by chrisar45** [comment]
La ultima que esta aqui

**Comment by klzns** [comment]
Can you please type:

```sh
sudo rm -rf node_modules
npm install
```

And try again?

Also copy and paste the results of `npm -v` and `node -v`

**Comment by chrisar45** [comment]
en la consola me tira este error

[image: image.png]

**Comment by MScevola** [comment]
I was using a version with gulp, but I tried with grunt and ran just fine.
Now I'm adapting my repo to this version, anyway, somthing happened and
generated this issue..

**Comment by carloschneider** [comment]
@MScevola I'm also using gulp. But I'm just having timeout error in terminal.

**Comment by MScevola** [comment]
@carloschneider My tasks are running fine in terminal, the error happens when I access my.vtexlocal.com.br, and the validation entry keeps goin on loop

**Comment by MScevola** [comment]
People that are using gulp (@carloschneider ), I resolved my issue including the following lines after the function replaceHost at the speed-middleware.js

replaceReferer = function(rewriteReferer){
  return function(req, res, next){
    req.headers.referer = rewriteReferer(req.headers.referer)
    return next();
  };
};

**Comment by chrisar45** [comment]
El error esta en que no esta copiando la cooki de autenticacion al ambiente local, alguna idea de como hacerlo por coffee script
?

**Comment by klzns** [comment]
You can see how we do it in VTEX Speed here as an example:
https://github.com/vtex/speed/blob/master/Gruntfile.coffee#L33

You can use this tool to compile JS script to Coffee: http://js2.coffee/

I'm closing this issue since it's not a VTEX Speed issue.

Feel free to use this issue to discuss solutions for your own tools though.

**Comment by chrisar45** [comment]
si es un error del vtex speed ya que no me esta autenticando cuando me logeo

**Comment by MScevola** [comment]
The solution for gulkp is add the following line after declare portalProxyOptions.preserveHost as true:

portalProxyOptions.cookieRewrite = accountName + ".vtexlocal.com.br";

thats all folks!

**Comment by MScevola** [comment]
portalProxyOptions.cookieRewrite = accountName + ".vtexlocal.com.br";

**Comment by carloschneider** [comment]
@MScevola @klzns He's not using Gulp, I think. @chrisar45 right?

**Comment by chrisar45** [comment]
perfecto, solucionado, esa linea soluciono todo. muchas gracias @MScevola

**Comment by chrisar45** [comment]
Estoy usadno grunt pero se soluciono

**Comment by Gabo31102** [comment]
Hola, tengo el mismo problema estoy tratando de utilizar vtexlocal en googleChrome y entro en el loop infinito del login intento con mozilla firefox y si puedo acceder a mi tienda. Alguna sugerencia, gracias
