### ISSUE TITLE
Não é possível fazer login

### ISSUE THREAD

**Issue by jmaicon** [vtex/speed#43]
**Você quer pedir uma nova feature ou reportar um bug?**

Bug

**Qual o comportamento atual?**

Não é possível fazer login, assim que coloco a chave enviada por e-mail, a página solicita login novamente. O bug ocorre tanto com a chave ou sms.

**Se o comportamento atual é um bug, por favor, forneça os passos para reproduzir o problema.**

Rode o npm start e acesse http://localhost:80 ou accountName.vtexlocal.com.br

**Qual o comportamento esperado?**

Ao inserir a chave corretamente, fazer login normalmente e acessar a loja.

**Qual browser e sistema operacional são afetados por esse problema?**

Chrome, linux, última versão do speed.

**Comment by gfpaiva** [comment]
Acho que tem relação:
Qualquer coisa que tento fazer aqui que envolva o VTEXID no ambiente localhost dá esse erro no "start":
![capturar](https://user-images.githubusercontent.com/11557474/46314578-5a49e980-c5a1-11e8-9796-f2fb155e600b.PNG)

**Comment by jmaicon** [comment]
Cara tente usar outra porta: PORT=9000 npm start

Resolveu pra mim.

**Comment by abisewski** [comment]
Estou tendo o mesmo problema e não funcionou rodando o PORT=9000 npm start.

**Comment by abisewski** [comment]
Estava com o mesmo problema. Reiniciei o computador e voltou a funcionar. :)
