### ISSUE TITLE
No funciona bien el build

### ISSUE THREAD

**Issue by morant901** [vtex/speed#49]
Al compilara el proyecto no copia bien los archivos al "build/arquivos" y copia y pega los archivos dentro de las carpetas. es decir si creo una carpeta que se llama "sass" y dentro los archivos .scss y un "main.scss" que los contenga a todos, cuando hace el "task" simplemente copia y pega toda la carpeta "sass" dentro de la carpeta "build" pero no hace el compilado de los archivos, además tampoco hace el .min

Como lo había planteado el usuario @gpelaez tenían más orden los archivos y no había que poner en el root de la carpeta "src/arquivos" todos los elementos.

**Comment by klzns** [comment]
Do you mean a file structure like this?

```
src/
└── sass
    ├── foo.scss
    └── main.scss
```

After build:

```
build/
└── arquivos
    └── sass
        ├── ex.css
        └── main.css
```

Can you give an example what the expected output should be, please? I didn't understand the problem you are having.

**Comment by cdatehortuab** [comment]
He means when you build, grunt is preserving folder structure so you can't have subfolders for styles or scripts separately. You must have all the files directly under src/.

I will make a PR solving this.
