### ISSUE TITLE
Erro no vtexlocal por causa do 'myvtex'

### ISSUE THREAD

**Issue by diegomcsilva** [vtex/speed#54]
**Você quer pedir uma nova feature ou reportar um bug?**
Reportar um bug

**Qual o comportamento atual?**
As páginas retornam erro(Blocked/404).

**Se o comportamento atual é um bug, por favor, forneça os passos para reproduzir o problema.**
No Gruntfile.coffee adicionar o 'myvtex' no environment. Ficando assim: environment = process.env.VTEX_ENV or pkg.env or 'vtexcommercestable' or 'myvtex'

**Qual o comportamento esperado?**
As páginas não retornem erro.

**Qual browser e sistema operacional são afetados por esse problema?**
Todos

**Comment by brunotda** [comment]
Este bug do myvtex, ocorre devido a utilização do SSL, você precisa rodar a sua loja com https para não ter o retorno 404.

**Comment by diegomcsilva** [comment]
A legal! Na epoca eu consegui resolver desse jeito ai de cima. Mas Blz, Obrigado pelo feedback
