### ISSUE TITLE
Problema com cors

### ISSUE THREAD

**Issue by cogdd** [vtex/speed#55]
**Você quer pedir uma nova feature ou reportar um bug?**
Bug

**Qual o comportamento atual?**
Error 405 no retorno da API.
![image](https://user-images.githubusercontent.com/51338149/58827149-a78ec700-8618-11e9-8215-74d680c58aa8.png)

Retorno 200 ok no postman:
![image](https://user-images.githubusercontent.com/51338149/58827219-da38bf80-8618-11e9-86c1-f67de7d52bd8.png)

**Se o comportamento atual é um bug, por favor, forneça os passos para reproduzir o problema.**
Fazer requisição via dominio diferente. (No meu caso estou tentando acessar a api da vtex (na porta 80) em um ambiente local que simula o meu front-end em angular)

**Qual o comportamento esperado?**

Permitir o acesso a api.

**Qual browser e sistema operacional são afetados por esse problema?**
Google Chrome e Windows

**Comment by klzns** [comment]
Você deve usar o host:

`https://SUALOJA.vtexlocal.com.br/` ou `http://SUALOJA.vtexlocal.com.br/`

**Comment by cogdd** [comment]
Olá Breno, obrigado pela resposta.

O erro ainda continua.

**Comment by klzns** [comment]
@cogdd Qual URL vc esta acessando?

**Comment by cogdd** [comment]
http://MINHALOJA.vtexlocal.com.br/api/checkout/pub/postal-code/BRA/01310940

A resposta continua a mesma por conta do CORS, mas o teste via Postman a api retorna 200....

**Comment by klzns** [comment]
@cogdd Rodei o vtex speed normalmente aqui, fiz essa mesma chamada no front do Checkout e deu tudo certo.

Provavelmente o seu Speed esta mal configurado. Verifique se colocou o accountName no `package.json`:
https://github.com/vtex/speed/blob/master/package.json#L3

**Comment by cogdd** [comment]
Pior que o accountName está certinho.

A api está funcionando, pois o teste via postman retorna tudo certo também.

Como meu front-end com angular em desenvolvimento, esta numa porta diferente do speed tenho como autorizar no script do middleware?
