### ISSUE TITLE
Error login VTEXLOCAL Chrome

### ISSUE THREAD

**Issue by zeluizr** [vtex/speed#56]
**Você quer pedir uma nova feature ou reportar um bug?**
bug

**Qual o comportamento atual?**
No Chrome, quando tento fazer login no vtexlocal fica em loop e não consigo logar.
No Firefox, e outro consigo logar.

**Se o comportamento atual é um bug, por favor, forneça os passos para reproduzir o problema.**

**Qual o comportamento esperado?**
Logar no ambiente vtexlocal

**Qual browser e sistema operacional são afetados por esse problema?**
Chrome

**Comment by brunotda** [comment]
Da uma olhada nesta atualização que enviei.
#59

Basicamente forcei o modo https e o login voltou a funcionar.

**Comment by raphaelcorreaoct** [comment]
Eu resolvi atualizando minhas dependências. 

"serve-static": "^1.14.1",
"proxy-middleware": "^0.15.0",
 "connect-http-please": "^0.3.0",

**Comment by zeluizr** [comment]
fala ai @raphaelcorreaoct fiz a alteração que você falou, e nada.
Ele sempre fica resetando o Login, só consigo mesmo no Firefox e muito precario.
Nosso amigo @CaioCFV fez uma versão que funciona perfeito.
https://github.com/CaioCFV/vtex-local

**Comment by raphaelcorreaoct** [comment]
Boooa!! 
Achei bem legal o repo do @CaioCFV. 
Montei um também mas com webpack. Se quiser conferir o link ta [aqui](https://github.com/raphaelcorreaoct/vtex-speed-webpack)

**Comment by CaioCFV** [comment]
Gostei bastante dessa versão com webpack, vou testar com certeza!
