### ISSUE TITLE
Falha na versão do Node

### ISSUE THREAD

**Issue by zeluizr** [vtex/speed#9]
Quando executo o comando "npm install" ele diz que meu node e npm estão com versão mais novas que a que necessita... sabe o que pode estar acontecendo?

**Comment by firstdoit** [comment]
provavelmente é só um warning. isso impede o funcionamento?

Em 21 de janeiro de 2015 14:13, Ze Luiz Rodrigues <notifications@github.com>
escreveu:

> Quando executo o comando "npm install" ele diz que meu node e npm estão
> com versão mais novas que a que necessita... sabe o que pode estar
> acontecendo?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vtex/speed/issues/9>.
>



-- 
Att,
Guilherme Rodrigues - VTEX - Developer
lab.vtex.com
+55 21 9 88447814

Colabore com o pacote de dados do meu celular. Não utilize imagens em sua
assinatura.

**Comment by firstdoit** [comment]
De fato, isso é um mero warning. Não deve impedir o uso!
